server:
  debug: true
  name: "go-template"
  version: "0.1.0"
  port: ":8080"
  requestTimeout: "15s"
  readTimeout: "5s"
  writeTimeout: "10s"
  ctxDefaultTimeout: "15s"

database:
  host: "localhost"
  port: 5432
  userName: "postgres"
  password: "123123@Admin"
  database: "app_db"
  schema: "public"
  maxOpenConns: 25
  maxIdleConns: 5
  connMaxLifetime: "1h"
  connMaxIdleTime: "10m"
  options: ""
  debug: false

redis:
  mode: "single"
  username: ""
  password: ""
  masterName: ""
  poolSize: 10
  address:
    - "127.0.0.1:6379"

logger:
  level: "info"
  endcoding: "json"

mqtt:
  broker: "tcp://localhost:1883"
  clientID: "go-template"
  username: ""
  password: ""
  connectTimeout: "5s"
  keepAlive: "30s"

workers:
  userEvent:
    topic: "events/user"
    qos: 1

tracing:
  enabled: false
  endpoint: "localhost:4317"
  insecure: true
  sampleRatio: 1.0

adapters:
  product:
    baseURL: "https://6a32d564c6ca2aee4385ac36.mockapi.io/api/v1/mock-svc"
    timeout: "10s"
    keepAlive: "90s"
    retryCount: 3
    retryWait: "500ms"
    apiKey: ""
    debug: false